# Override เฉพาะค่าที่ต่างจาก values.yaml สำหรับ dev
replicaCount: 1

image:
  tag: "dev-4482fc8"

env:
  message: "Hello from DEV!!"

ingress:
  enabled: true
  host: app-dev.hs-network.info
  externalDns:
    enabled: true
