# Override เฉพาะค่าที่ต่างจาก values.yaml สำหรับ prod
replicaCount: 3

image:
  tag: "v2.0.1"

env:
  name: "production"
  message: "Hello from PRODUCTION"

ingress:
  enabled: true
  host: app-prod.hs-network.info
  externalDns:
    enabled: true

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi
