# Override เฉพาะค่าที่ต่างจาก values.yaml สำหรับ dev
replicaCount: 1

image:
  tag: "dev-1d87d3d"

env:
  message: "Hello from DEV"

ingress:
  enabled: true
  # ค่านี้จะถูก CI เขียนทับจาก GitHub Actions Variable "INGRESS_HOST_DEV"
  # ทุกครั้งที่ deploy-dev.yaml รัน (ดู .github/workflows/deploy-dev.yaml)
  host: hello-app.dev.local
