apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-app-prod
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/hscrystal/wsp.git
    targetRevision: main
    path: charts/hello-app
    helm:
      valueFiles:
        - values.yaml
        - values-prod.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: hello-app-prod

  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
